---

- name: hosts | exchange hostsnames in hosts file
  blockinfile:
    path: /etc/hosts
    block: |
      {% if hostvars[item]['vswitch_ip'] is defined %}
      {{ hostvars[item]['vswitch_ip'] }} {{ hostvars[item]['ansible_hostname'] }}
      {% endif %}
      {{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_hostname'] }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ hostvars[item]['ansible_hostname'] }}"
  loop: "{{ play_hosts }}"
