---
- name: sshd | development configuration
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^^#?PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^#?AllowTcpForwarding"
      line: "AllowTcpForwarding yes"
    - regexp: "^#?AllowAgentForwarding"
      line: "AllowAgentForwarding yes"
    - regexp: "^#?MaxAuthTries"
      line: "MaxAuthTries 2"
    - regexp: "^#?UseDNS"
      line: "UseDNS no"
    - regexp: "^#?TCPKeepAlive"
      line: "TCPKeepAlive yes"
    - regexp: "^#?PermitRootLogin"
      line: "PermitRootLogin yes"
    - regexp: "^#?MaxSessions"
      line: "MaxSessions 10"
  notify: restart sshd
