---
- name: packages | install python3-apt
  apt:
    name: python3-apt
    state: present

- name: packages | upgrade all existing packages to their latest version
  apt:
    name: "*"
    state: latest
    update_cache: true

- name: packages | install default packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - openssh-server
      - gnupg-agent
      - iproute2
      - iptables
      - iptables-persistent
      - netfilter-persistent
      - software-properties-common
      - unattended-upgrades
      - acl
      - dirmngr
      - python3
      - python3-pip

      # dev
      - vim
      - curl
      - wget
      - bash-completion
